---
- name: Instalacja narzedzi
  hosts: localhost
  connection: local
  tasks:
  - name: Instalacja Python-PIP 
    apt:
      name: python3-pip
      update_cache: yes
      cache_valid_time: 432000
    become: true
  - name: Install lxml
    pip:
      name: lxml 
    become: true
  - name: Pobranie artifactu
    maven_artifact:
      group_id: pl.jp
      artifact_id: jp
      repository_url: /http://10.200.0.159/:8081/artifactory/libs-release-local
      username: admin 
      password: Pandapass1
      dest: ./application.jar


- name: Instalacja srodowiska
  hosts: aws
  tasks:
  - name: Instalacja Javy (JRE)
    apt:
      name: default-jre
      update_cache: yes
    become: true
- name: Deploy aplikacji 
  hosts: aws
  tasks:
  - name: Kopiowanie aplikacji
    copy:
      src: ./application.jar
      dest: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      mode: '0644'
  - name: Kopiowanie definicji serwisu
    copy:
      src: ./application.service 
      dest: /etc/systemd/system/ 
      owner: ubuntu
      group: ubuntu
      mode: '0744'
    become: true
  - name: Uruchomienie aplikacji
    service:
      name: application
      state: restarted 
    become: true